### ISSUE TITLE
missing include headers

### ISSUE THREAD

**Issue by blshkv** [libyal/libvshadow#10] opened 2017-07-20 08:36 UTC
I was getting relevant error messages (XXX not defined) and had to add the follow two lines:
```
--- vshadowtools/vshadowmount.c.orig    2017-07-15 15:18:38.000000000 +0800
+++ vshadowtools/vshadowmount.c 2017-07-20 16:26:48.334872904 +0800
@@ -26,6 +26,10 @@
 #include <types.h>
 #include <wide_string.h>
 
+/* blshkv */
+#include <asm-generic/errno-base.h>
+#include <errno.h>
+
 #include <stdio.h>
 
 #if defined( HAVE_ERRNO_H )

```

No idea about the second one because HAVE_ERRNO_H suppose to add it

**Comment by blshkv** [comment] 2017-07-20 08:41
gcc (Gentoo Hardened 5.4.0-r3 p1.3, pie-0.6.5) 5.4.0
sys-kernel/linux-headers-4.4 (/usr/include/asm-generic/errno-base.h)
sys-libs/glibc-2.23-r4 (/usr/include/errno.h)

**Comment by joachimmetz** [comment] 2017-07-20 14:18
can you provide me with the relevant error messages. thx in advance

**Comment by blshkv** [comment] 2017-07-20 21:52
here we go:
```
make[1]: Entering directory '/var/tmp/portage/app-forensics/libvshadow-20170715_alpha/work/libvshadow-20170715/vshadowtools'
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o debug_handle.o debug_handle.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o vshadowdebug.o vshadowdebug.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o vshadowtools_getopt.o vshadowtools_getopt.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o vshadowtools_output.o vshadowtools_output.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o vshadowtools_signal.o vshadowtools_signal.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o byte_size_string.o byte_size_string.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o info_handle.o info_handle.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o vshadowinfo.o vshadowinfo.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o mount_handle.o mount_handle.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -march=native -O2 -pipe -Wall -c -o vshadowmount.o vshadowmount.c
/bin/sh ../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc  -march=native -O2 -pipe -Wall  -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -o vshadowdebug debug_handle.o vshadowdebug.o vshadowtools_getopt.o vshadowtools_output.o vshadowtools_signal.o -lfguid -lfdatetime -lbfio -lcpath -lcfile -luna -lcsplit -lcdata -lcnotify -lclocale ../libvshadow/libvshadow.la -lcerror  -ldl 
vshadowmount.c: In function ‘vshadowmount_fuse_open’:
vshadowmount.c:185:13: error: ‘EINVAL’ undeclared (first use in this function)
   result = -EINVAL;
             ^
vshadowmount.c:185:13: note: each undeclared identifier is reported only once for each function it appears in
vshadowmount.c:219:13: error: ‘ENOENT’ undeclared (first use in this function)
   result = -ENOENT;
             ^
vshadowmount.c:232:13: error: ‘EACCES’ undeclared (first use in this function)
   result = -EACCES;
             ^
vshadowmount.c: In function ‘vshadowmount_fuse_read’:
vshadowmount.c:276:13: error: ‘EINVAL’ undeclared (first use in this function)
   result = -EINVAL;
             ^
vshadowmount.c:323:13: error: ‘ENOENT’ undeclared (first use in this function)
   result = -ENOENT;
             ^
vshadowmount.c:357:13: error: ‘EIO’ undeclared (first use in this function)
   result = -EIO;
             ^
vshadowmount.c: In function ‘vshadowmount_fuse_readdir’:
vshadowmount.c:602:13: error: ‘EINVAL’ undeclared (first use in this function)
   result = -EINVAL;
             ^
vshadowmount.c:619:13: error: ‘ENOENT’ undeclared (first use in this function)
   result = -ENOENT;
             ^
vshadowmount.c:635:13: error: ‘errno’ undeclared (first use in this function)
   result = -errno;
             ^
vshadowmount.c:651:13: error: ‘EIO’ undeclared (first use in this function)
   result = -EIO;
             ^
vshadowmount.c: In function ‘vshadowmount_fuse_getattr’:
vshadowmount.c:800:30: error: ‘ENOENT’ undeclared (first use in this function)
  int result               = -ENOENT;
                              ^
vshadowmount.c:811:13: error: ‘EINVAL’ undeclared (first use in this function)
   result = -EINVAL;
             ^
vshadowmount.c:840:12: error: ‘errno’ undeclared (first use in this function)
   result = errno;
            ^
vshadowmount.c:876:15: error: ‘EIO’ undeclared (first use in this function)
     result = -EIO;
               ^
make[1]: *** [Makefile:764: vshadowmount.o] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: link: x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -Wall -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -o .libs/vshadowdebug debug_handle.o vshadowdebug.o vshadowtools_getopt.o vshadowtools_output.o vshadowtools_signal.o  ../libvshadow/.libs/libvshadow.so -lcthreads -lcdata -lclocale -lcnotify -lcsplit -luna -lcfile -lcpath -lbfio -lfdatetime -lfguid -lcerror -ldl
make[1]: Leaving directory '/var/tmp/portage/app-forensics/libvshadow-20170715_alpha/work/libvshadow-20170715/vshadowtools'
make: *** [Makefile:725: all-recursive] Error 1
```

**Comment by joachimmetz** [comment] 2017-07-21 04:17
> No idea about the second one because HAVE_ERRNO_H suppose to add it

could you also provide me with what config.log indicates about detecting errno.h (or attach the whole config.log)

**Comment by blshkv** [comment] 2017-07-21 05:29
Here we go:
https://gist.github.com/blshkv/c8f9f6183d912504d23c30c08b1755c4

**Comment by blshkv** [comment] 2017-07-21 05:33
ENOENT and EINVAL are defined in the /usr/include/asm-generic/errno-base.h and that one may be missing.

errno was not detected (/usr/include/errno.h ) for no reason

**Comment by joachimmetz** [comment] 2017-07-21 05:55
> ENOENT and EINVAL are defined in the /usr/include/asm-generic/errno-base.h and that header may be missing.

including errno.h should suffice, errno.h should include asm-generic/errno-base.h, because this might differ per platform.

> errno was not detected (/usr/include/errno.h) for no reason

I'll have a look, when time permits, if this might be missing from configure scripts

**Comment by joachimmetz** [comment] 2019-02-07 05:58
Gist with config.log no longer available, was unable to reproduce issue on other distributions. Closing issue, this looks something pentoo specific.

**Closed by joachimmetz** 2019-02-07 05:58 UTC
Labels: needs a closer look

**Comment by blshkv** [comment] 2019-02-07 08:47
I have tried the latest 20190127 and can't reproduce the issue either. You must have fixed it during these 1.5 years. The configuration script is able to find the header now, I can see ```HAVE_ERRNO_H 1``` in the config.log.

**Comment by joachimmetz** [comment] 2019-02-07 09:06
> You must have fixed it during these 1.5 years.

That or pentoo changed and took away an underlying issue that broke the detection in the first place. I would expect a maintainer of a distro maintainers is able to troubleshoot deployment issue specific to their distro.

**Comment by blshkv** [comment] 2019-02-07 09:23
yes, it were a number of changes on our side as well during that long period. Specifically, sys-kernel/linux-headers-4.4 package was upgraded to 4.14 but I have no time to verify that. I also expect a faster communication with upstream (months, not years), so we could troubleshoot any issues.

**Comment by joachimmetz** [comment] 2019-02-07 09:41
> I also expect a faster communication with upstream (months, not years), so we could troubleshoot any issues.

I happy to take away this assumption. This is unrealistic, I'm a single person maintaining many projects and there are tons of distros. So this model does not scale especially if maintainers can't help themselves.

**Comment by blshkv** [comment] 2019-02-07 09:50
This is great, luckily we can fix any bugs (as we fixed this one here https://github.com/libyal/libvshadow/issues/10#ref-commit-fe40d4f) and happy to contribute back. It is up to an upstream to accept it. However, we will stop doing so if we feel it is not worst it.

**Comment by joachimmetz** [comment] 2019-02-07 09:55
https://github.com/pentoo/pentoo-overlay/commit/fe40d4fd46ab4850f5db15a14f8b46a26fa29240 is not a fix, its a work-around. If you only would provide fixes especially those that consider this is cross-platform project not a pentoo-only project. I have to say the interaction with other distro maintainers is much more productive than with you. I'm fine you remove the projects from pentoo, so you don't have to work on deploying them and me listening to you whine.

**Comment by blshkv** [comment] 2019-02-07 10:05
I know it was a workaround, it written "workaround" in the comment. LOL. The idea was to demonstrate myself where the problem is as I had zero help from your side even after I provided all the requested information. It is hard to understand somebody's else code so I expected a little hits from you such as "upgrade sys-kernel/linux-headers since I have a different version".

I'm not sure how you expect "cross-platform project" with the current attitude. 
Good luck.

**Comment by joachimmetz** [comment] 2019-02-07 10:08
> I'm not sure how you expect "cross-platform project" with the current attitude.

Please go be frustrated somewhere else.
